// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoBiblioteca.Dados;

#nullable disable

namespace ProjetoBiblioteca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906233647_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBiblioteca.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NACIONALIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("AUTORES", (string)null);
                });

            modelBuilder.Entity("ProjetoBiblioteca.Models.AutorLivro", b =>
                {
                    b.Property<int>("AutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AUTORID");

                    b.Property<int>("LivroId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LIVROID");

                    b.HasKey("AutorId", "LivroId");

                    b.HasIndex("LivroId");

                    b.ToTable("AUTORESLIVROS", (string)null);
                });

            modelBuilder.Entity("ProjetoBiblioteca.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANOPUBLICACAO");

                    b.Property<string>("Editora")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EDITORA");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.ToTable("LIVROS", (string)null);
                });

            modelBuilder.Entity("ProjetoBiblioteca.Models.AutorLivro", b =>
                {
                    b.HasOne("ProjetoBiblioteca.Models.Autor", "Autor")
                        .WithMany("AutoresLivros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoBiblioteca.Models.Livro", "Livro")
                        .WithMany("AutoresLivros")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("ProjetoBiblioteca.Models.Autor", b =>
                {
                    b.Navigation("AutoresLivros");
                });

            modelBuilder.Entity("ProjetoBiblioteca.Models.Livro", b =>
                {
                    b.Navigation("AutoresLivros");
                });
#pragma warning restore 612, 618
        }
    }
}
